version: '3.8'
services:
  db-kpis:
    image: postgres:15
    container_name: cordillera-db-kpis
    environment:
      POSTGRES_DB: kpis_db
      POSTGRES_USER: user_cordillera
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_kpis:/var/lib/postgresql/data

volumes:
  postgres_data_kpis:
