version: '3.8'
services:
  # Base de Datos de KPIs
  db-kpis:
    image: postgres:15
    container_name: cordillera-db-kpis
    environment:
      POSTGRES_USER: ${DB_KPIS_USER}
      POSTGRES_PASSWORD: ${DB_KPIS_PASSWORD}
      POSTGRES_DB: ${DB_KPIS_NAME}
    ports:
      - "5432:5432"

  # Base de Datos de Metas/Equipos
  db-metas:
    image: postgres:15
    container_name: cordillera-db-metas
    environment:
      POSTGRES_USER: ${DB_METAS_USER}
      POSTGRES_PASSWORD: ${DB_METAS_PASSWORD}
      POSTGRES_DB: ${DB_METAS_NAME}
    ports:
      - "5433:5432"

  db-equipos:
      image: postgres:15
      container_name: cordillera-db-equipos
      environment:
        POSTGRES_USER: ${DB_EQUIPOS_USER}
        POSTGRES_PASSWORD: ${DB_EQUIPOS_PASSWORD}
        POSTGRES_DB: ${DB_EQUIPOS_NAME}
      ports:
        - "5434:5432"  