server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: todas las rutas sirven index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia API Gateway
    location /gw/ {
        proxy_pass http://api-gateway:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia ms-kpis
    location /ms/ {
        proxy_pass http://ms-kpis:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia ms-metas
    location /ms-mt/ {
        proxy_pass http://ms-metas:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia ms-equipos
    location /ms-eq/ {
        proxy_pass http://ms-equipos:3003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
